<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?php echo C('shopName');?> - <?php echo $title;?> </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="{:C('css')}/general.css" rel="stylesheet" type="text/css" />
    <link href="{:C('css')}/main.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="{:C('js')}/jquery.js"></script>
    <style type="text/css">
        /*first-cell做相对定位，这边做绝对定位*/
        .goods_thumb{display: none; position: absolute;z-index: 3;left: -100px;top:-3px}
        .goods_pic{
            cursor: pointer;
        };
        .goods_pic a {text-decoration: none}
    </style>
    <script type="text/javascript">
        //鼠标滑过显示品牌图片的动态效果
        $(function () {
            $('.goods_pic').hover(function () {
                $(this).find('img').show();
            },function () {
                $(this).find('img').hide();
            });
        })

        $(function () {
            //单选不为真，取消全选
            var checkSize = 0;
            batchSelect(checkSize);
            $("#allCheck").click(function () {
                if($(this).attr("checked"))
                {
                    $(".goods_id").attr("checked","checked");
                    checkSize = $('.goods_id').size();
                }
                else
                {
                    $(".goods_id").attr("checked","");
                    checkSize = 0;
                }
                batchSelect(checkSize);
            });

            $('.goods_id').click(function () {

                if(!$(this).attr("checked"))
                {
                    $("#allCheck").attr("checked","");
                    checkSize--;
                    if(checkSize < 0)
                    {
                        checkSize = 0;
                    }
//                alert(checkSize);
                }
                else
                {
                    checkSize++;
                    if(checkSize > $('.goods_id').size())
                    {
                        checkSize = $('.goods_id').size();
                    }
//                alert(checkSize);
                    if(checkSize ==  $('.goods_id').size())
                    {
                        $("#allCheck").attr("checked","checked");
                    }
                }
                batchSelect(checkSize);
            });

        });
        //批量删除效果
        function batchSelect(num) {
            if(num > 0)
            {
                $('#batch').attr("disabled","");
            }
            else
            {
                $('#batch').attr("disabled","disabled");
            }
        }

        //类型跳转
        $('#sendType').change(function () {
            location.href =  '<?php echo U("Admin/Sms/search","",false);?>'+"/send_type/"+$(this).val();
        });


    </script>
</head>
<body>
<h1>
    <span class="action-span"><a href="<?php echo U("Admin/Goods/add")?>">添加新商品</a></span>
    <span class="action-span1"><a href="<?php echo U("Admin/Index/index")?>"><?php echo C('shopName');?></a></span>
    <span id="search_id" class="action-span1"> -<?php echo $title;?> </span>
    <div style="clear:both"></div>
</h1>
<div class="form-div">
    <form action="<?php echo U('Admin/Goods/lst');?>" name="searchForm" method="get">
        <img src="{:C('img')}/icon_search.gif" width="26" height="22" border="0" alt="search" />
        <input type="text" name="keyword" size="50" placeholder="商品名称|商品sku" value="<?php echo $_GET['keyword']?>"/>
        <input type="submit" value=" 搜索 " class="button" />
    </form>
</div>
<form method="post" action="<?php echo U('Admin/Goods/batchTrash');?>" name="listForm">
    <div class="list-div" id="listDiv">
        <table cellpadding="3" cellspacing="1">
            <tr>
                <th><input id="allCheck" type="checkbox" class="goods_id"/>商品id</th>
                <th>商品名称</th>
                <th>库存量</th>
                <th>市场价</th>
                <th>本店价</th>
                <th>商品sku</th>
                <th>是否上架</th>
                <th>操作</th>
            </tr>
            <?php foreach ($data as $k=>$v):?>
            <tr>
                <td align="left"><input class="goods_id"  type="checkbox" name="goods_id[]" value="<?php echo $v['id'];?>"/><?php echo $v['id'];?></td>
                <td align="left" class="goods_pic">
                    <a  href="<?php echo U("Admin/Goods/save",array('id'=>$v['id']))?>">
                        <?php echo $v['goods_name'];?>
                    </a>
                    <?php if(!empty($v['sm_logo'])):?>
                    <a href="<?php echo U("Home/Goods/detail",array('id'=>$v['id']))?>" target="_blank" title="查看"><img src="<?php echo $v['sm_logo'];?>" class="goods_thumb"/></a>
                    <?php endif; ?>
                </td>
                <td align="center"><?php echo $v['goods_number'];?></td>
                <td align="center"><?php echo $v['market_price'];?></td>
                <td align="center"><?php echo $v['shop_price'];?></td>
                <td align="center"><?php echo $v['goods_sn'];?></td>
                <td align="center">
                    <?php if($v['is_on_sale']==1):?>
                    <img src="<?php echo C('img')?>/yes.gif" />
                    <?php else:?>
                    <img src="<?php echo C('img')?>/no.gif" />
                    <?php endif;?>
                </td>
                <td align="center">
                    <a href="<?php echo U("Home/Goods/detail",array('id'=>$v['id']))?>"  target="_blank" title="查看"> <img src="<?php echo C('img')?>/icon_view.gif" /></a>
                    <a href="<?php echo U("Admin/Goods/save",array('id'=>$v['id']))?>" title="编辑"> <img src="<?php echo C('img')?>/icon_edit.gif" /></a>
                    <a onclick="return confirm('确定要删除吗');" href="<?php echo U("Admin/Goods/trash",array('id'=>$v['id']))?>" title="删除"><img src="<?php echo C('img')?>/icon_trash.gif" /></a>
                    <?php if(D('Goods')->haveRadioType($v['id'])):?>
                    <a  href="<?php echo U("Admin/Goods/productList",array('id'=>$v['id']))?>" title="商品货号"><img src="<?php echo C('img')?>/icon_docs.gif" /></a>
                    <?php endif;?>
                </td>
            </tr>
            <?php endforeach;?>
            <tr>
                <td width="12%"><input onclick="return confirm('确定要放到回收站吗?');" id="batch" type="submit" value="批量回收"></td>
                <td align="center" nowrap="true" colspan="7">
                    <?php echo $page; ?>
                </td>
            </tr>
        </table>
    </div>
</form>

<?php include_once "/assets/template/footer.php";?>
</body>
</html>