<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?php echo C('shopName');?> - <?php echo $title;?> </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="{:C('css')}/general.css" rel="stylesheet" type="text/css" />
    <link href="{:C('css')}/main.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="{:C('js')}/jquery.js"></script>
    <style type="text/css">
        /*first-cell做相对定位，这边做绝对定位*/
        .goods_thumb{display: none; position: absolute;z-index: 3;left: 0px;top:-3px}
        .goods_pic{
            cursor: pointer;
        };
        .goods_pic a {text-decoration: none}
    </style>
    <script type="text/javascript">
        //鼠标滑过显示品牌图片的动态效果
        $(function () {
            $('.goods_pic').hover(function () {
                $(this).find('img').show();
            },function () {
                $(this).find('img').hide();
            });
        })
    </script>
</head>
<body>
<h1>
    <span class="action-span"><a href="<?php echo U("Admin/Goods/add")?>">添加新商品</a></span>
    <span class="action-span1"><a href="<?php echo U("Admin/Index/index")?>"><?php echo C('shopName');?></a></span>
    <span id="search_id" class="action-span1"> -<?php echo $title;?> </span>
    <div style="clear:both"></div>
</h1>
<div class="form-div">
    <form action="" name="searchForm">
        <img src="{:C('img')}/icon_search.gif" width="26" height="22" border="0" alt="search" />
        <input type="text" name="brand_name" size="15" />
        <input type="submit" value=" 搜索 " class="button" />
    </form>
</div>
<form method="post" action="" name="listForm">
    <div class="list-div" id="listDiv">
        <table cellpadding="3" cellspacing="1">
            <tr>
                <th><input type="checkbox" class="goods_id"/>商品id</th>
                <th>商品名称</th>
                <th>库存量</th>
                <th>市场价</th>
                <th>本店价</th>
                <th>商品sku</th>
                <th>是否上架</th>
                <th>操作</th>
            </tr>
            <?php foreach ($data as $k=>$v):?>
            <tr>
                <td align="center"><input type="checkbox" name="goods_id[]" value="<?php echo $v['id'];?>"/><?php echo $v['id'];?></td>
                <td align="center" class="goods_pic">
                    <a  href="<?php echo U("Admin/Goods/save",array('id'=>$v['id']))?>">
                        <?php echo $v['goods_name'];?>
                    </a>
                    <?php if(!empty($v['sm_logo'])):?>
                    <img src="<?php echo $v['sm_logo'];?>" class="goods_thumb"/>
                    <?php endif; ?>
                </td>
                <td align="center"><?php echo $v['goods_number'];?></td>
                <td align="center"><?php echo $v['market_price'];?></td>
                <td align="center"><?php echo $v['shop_price'];?></td>
                <td align="center"><?php echo $v['goods_sn'];?></td>
                <td align="center"><?php echo $v['is_on_sale']==1?'上架':'下架'?></td>
                <td align="center">
                    <a href="<?php echo U("Admin/Goods/save",array('id'=>$v['id']))?>" title="编辑">编辑</a> |
                    <a onclick="return confirm('确定要删除吗');" href="<?php echo U("Admin/Goods/delete",array('id'=>$v['id']))?>" title="删除">移除</a>
                </td>
            </tr>
            <?php endforeach;?>
            <tr>
                <td align="center" nowrap="true" colspan="8">
                    <div id="turn-page">
                        <?php echo $page;?>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</form>

<?php include_once "/assets/template/footer.php";?>
</body>
</html>