<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?php echo C('shopName');?> - 修改商品 </title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="{:C('css')}/general.css" rel="stylesheet" type="text/css" />
<link href="{:C('css')}/main.css" rel="stylesheet" type="text/css" />
<script src="{:C('js')}/jquery-1.4.2.min.js"></script>
<script src="{:C('ueditor')}/ueditor.config.js"></script>
<script src="{:C('ueditor')}/ueditor.all.min.js"></script>
</head>
<body>
<h1>
    <span class="action-span"><a href="<?php echo U("Admin/Goods/lst")?>">商品列表</a>
    </span>
    <span class="action-span1"><a href="<?php echo U("Admin/Index/index")?>"><?php echo C('shopName');?></a></span>
    <span id="search_id" class="action-span1"> - 修改商品 </span>
    <div style="clear:both"></div>
</h1>

<div class="tab-div">
    <div id="tabbar-div">
        <p>
            <span class="tab-front basic-info">基本信息</span>
            <span class="tab-back">商品描述</span>
            <span class="tab-back">会员价格</span>
            <span class="tab-back">商品属性</span>
            <span class="tab-back  gallery">商品相册</span>
        </p>
    </div>
    <form enctype="multipart/form-data" action="<?php echo U("Admin/Goods/save")?>" method="post">
    <div id="tabbody-div" class="tabbody-div">
            <table width="90%" id="general-table" align="center">
                <input type="hidden" id="logo" size="40" name="goods[logo]" />
                <input type="hidden" name="id" value="<?php echo $goods['id'];?>" />
                <tr>
                    <td class="label">上传商品图片：</td>
                    <td>
                        <?php if(!empty($goods['sm_logo'])):?>
                            <img id="pre_img" src="<?php echo $goods['sm_logo'];?>"/>
                        <?php else:?>
                            <img id="pre_img" src="<?php echo C('img');?>/goods_logo.jpg"/>
                        <?php endif;?>
                        <input id="selImg" type="button" value="选择图片" />
                    </td>
                </tr>
                <tr>
                    <td class="label">商品名称：</td>
                    <td><input type="text" name="goods[goods_name]" value="<?php echo $goods[goods_name]?>"size="80" />
                    <span class="require-field">*</span></td>
                </tr>
                <tr>
                    <td class="label">商品sku： </td>
                    <td>
                        <input type="text" name="goods[goods_sn]" value="<?php echo $goods[goods_sn]?>" size="20"/>
                        <span id="goods_sn_notice"></span><br />
                        <span class="notice-span"id="noticeGoodsSN">商品sku必须唯一，不要使用中文</span>
                    </td>
                </tr>
                <tr>
                    <td class="label">商品分类：</td>
                    <td>
                        <select name="goods[cat_id]">
                            <option value="">请选择...</option>
                            <?php foreach ($categoryData as $k=>$v): ?>
                                <option  value="<?php echo $v['id'];?>"
                                    <?php if($v['id'] ==  $goods['cat_id']):?>
                                        selected="selected"
                                    <?php endif;?>
                                         style="padding-left: <?php echo 25*$v['level']?>px"><?php echo $v['cat_name'];?></option>
                            <?php endforeach; ?>
                        </select>
                        <span class="require-field">*</span>
                    </td>
                </tr>
                <tr>
                    <td class="label">商品品牌：</td>
                    <td>
                        <select name="goods[brand_id]">
                            <option value="">请选择...</option>
                            <?php foreach ($brandData as $k=>$v): ?>
                                <option
                                    <?php if($v['brand_id'] ==  $goods['brand_id']):?>
                                        selected="selected"
                                    <?php endif;?>
                                    value="<?php echo $v['brand_id'];?>"><?php echo $v['brand_name'];?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label">本店售价：</td>
                    <td>
                        <input type="text" name="goods[shop_price]" value="<?php echo $goods[shop_price]?>" size="20"/>
                        <span class="require-field">*</span>
                    </td>
                </tr>
                <tr>
                    <td class="label">市场售价：</td>
                    <td>
                        <input type="text" name="goods[market_price]" value="<?php echo $goods[market_price]?>" size="20" />
                    </td>
                </tr>
                <tr>
                    <td class="label">商品数量：</td>
                    <td>
                        <input type="text" name="goods[goods_number]" size="8" value="<?php echo $goods[goods_number]?>"/>
                    </td>
                </tr>
                <tr>
                    <td class="label">商品重量：</td>
                    <td>
                        <input type="text" name="goods[weight]" size="8" value="<?php echo $goods[weight]?>"/>
                        <select name="goods[weight_unit]">
                            <?php if($goods[weight_unit]  == 'g'):?>
                            <option value="g" selected="selected">克</option>
                            <option value="kg">千克</option>
                            <?php endif;?>
                            <?php if($goods[weight_unit]  == 'kg'):?>
                            <option value="g">克</option>
                            <option value="kg" selected="selected">千克</option>
                            <?php endif;?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label">是否上架：</td>
                    <td>
                        <input type="radio" <?php if($goods[is_on_sale] == 1):?> checked="checked"<?php endif;?>  name="goods[is_on_sale]" value="1"/> 是
                        <input type="radio" <?php if($goods[is_on_sale] == 0):?> checked="checked"<?php endif;?>  name="goods[is_on_sale]" value="0"/> 否
                    </td>
                </tr>
                <tr>
                    <td class="label">是否包邮：</td>
                    <td>
                        <input type="radio" <?php if($goods[no_postage] == 1):?> checked="checked"<?php endif;?>  name="goods[no_postage]" value="1"/> 是
                        <input type="radio" <?php if($goods[no_postage] == 0):?> checked="checked"<?php endif;?> name="goods[no_postage]" value="0"/> 否
                    </td>
                </tr>
            </table>

    </div>
    <!--商品描述开始-->
    <div class="tabbody-div" style="display:none;">
        <textarea name="goods[goods_desc]" id="goods_desc"><?php echo $goods[goods_desc]?></textarea>
        <script>
            // 把textarea替换成一个编辑器
            UE.getEditor('goods_desc',{
                initialFrameWidth:"100%",
                initialFrameHeight:"300"
            });
        </script>
    </div>
     <!--商品描述结束-->
    <!--会员价格开始-->
    <div class="tabbody-div" style="display:none;">
        <p style="text-align:center;color: green">如果不填，代表使用会员等级的折扣率</p>
        <table width="100%">
            <?php foreach ($userRankData as $k => $v): ?>
            <tr>
                <td class="label"><?php echo $v['level_name'];?>:</td>
                <td><input type="text" name="member_price[<?php echo $v['id']?>]"  value="<?php echo $mpData[$v['id']]?>"/></td>
            </tr>
            <?php endforeach;?>

        </table>
    </div>
    <!--会员价格结束-->
    <div class="tabbody-div" style="display:none;">
        <table width="100%" id="attrContent">
            <tr>
                <td class="label">商品类型:</td>
                <td>
                    <select id="type_id" name="goods[type_id]">
                        <option value="">请选择商品类型</option>
                        <?php foreach ($goodsTypeData as $k=>$v):?>
                        <option
                            <?php if($v['id'] ==  $goods['type_id']):?>
                                selected="selected"
                            <?php endif;?>
                            value="<?php echo $v['id']?>"><?php echo $v['type_name']?></option>
                        <?php endforeach;?>
                    </select>
                </td>
            </tr>
            <?php
            if($goods['type_id'] != '')
            {
                $type_id = $goods['type_id'];
                // 取出当前商品所有的属性
                $goodsAttrModel  = D('GoodsAttr');
                $goodsAttrData = $goodsAttrModel->where(array('goods_id'=>$goods['id']))->select();
//                dump($goodsAttrData);

                $AttributeModel = D('Attribute');
                $attributeData = $AttributeModel->where(array('goods_type_id'=>$type_id))->select();
//                dump($attributeData);
                foreach ($attributeData as $k=>$v)
                {

                    if($v['attr_type'] == 0) //唯一属性
                    {
                        // 找出当前这件商品这个属性的值是多少
                        foreach ($goodsAttrData as $k1 => $v1)
                        {
                            if($v1['attr_id'] == $v['id'])
                            {
                                $_attrVal = $v1['attr_value'];
                                break ;
                            }
                        }

                        if(empty($v['attr_value']))
                        {
                            echo '<tr><td class="label">'.$v['attr_name'].'</td><td><input type="text" value="'.$_attrVal.'"/></td></tr>';
                        }
                        else
                        {
                            echo '<tr><td class="label">'.$v['attr_name'].'</td><td>';
                            $_val = explode(',', trim($v['attr_value']));
                            echo '<select style="width:120px;" name="goods_attr['.$v['id'].']">';
                            foreach ($_val as $k1 => $v1)
                            {
                                if($v1 == $_attrVal)
                                    $selected = ' selected="selected" ';
                                else
                                    $selected = '';
                                echo '<option '.$selected.' value="'.$v1.'">'.$v1.'</option>';
                            }
                            echo '</select>';
                            echo '</td></tr>';
                        }
                    }

                    if($v['attr_type'] == 1) //单选属性
                    {
                        // 这个属性用来判断是否第一次遇到某一个属性
                        $_hasArr = array();
                        // 如果属性是多选的属性那么就有可能需要输出多个select框，所以这里要循环商品拥有的所有的属性
                        foreach ($goodsAttrData as $k2 => $v2)
                        {
                            if($v2['attr_id'] != $v['id'])
                                continue ;
                            // 判断这个属性是否是第一次遇到
                            if(!in_array($v['id'], $_hasArr))
                            {
                                $_hasArr[] = $v['id'];
                                $_atext = '[+]';
                            }
                            else
                                $_atext = '[-]';
                            $_val = explode(',', trim($v['attr_value']));
                            echo '<tr><td class="label">'.$v['attr_name'].'</td><td>';
                            // 输出属性的下拉框
                            echo '<a href="javascript:void(0);" onclick="addANewAttRow(this)">'.$_atext.'</a>
			                <select style="width:120px;"  name="goods_attr['.$v['id'].'][]">';
                            foreach ($_val as $k1 => $v1)
                            {
                                if($v1 == $v2['attr_value'])
                                    $selected = ' selected="selected" ';
                                else
                                    $selected = '';
                                echo '<option '.$selected.' value="'.$v1.'">'.$v1.'</option>';
                            }
                            echo '</select>
                            <input value="'.$v2['attr_price'].'" type="text" name="attr_price['.$v['id'].'][]" />
                            ';
                            echo '</td></tr>';
                        }

                    }
                }
            }

            ?>

        </table>

    </div>
        <style>
            #bpre_img li{margin:5px;float:left;list-style-type: none}
        </style>
    <div class="tabbody-div" style="display:none;">
        <div class="gallery" style="margin-top: 20px;margin-left: 50px;">
            <input id="selBImg" type="button" value="选择图片" />
            <ul id="bpre_img">
                <?php foreach ($gpData as $k => $v): ?>
                    <li>
                        <input type="hidden" name="OldGoodsPic[]" value="<?php echo $v['id']; ?>" />
                        <img src="<?php echo $v['sm_logo']; ?>" /><br />
                        <a onclick="this.parentNode.parentNode.removeChild(this.parentNode);" href="javascript:void(0);">[-]</a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <div style="clear: both"></div>

        <div class="button-div">
            <input type="submit" value=" 确定 " class="button"/>
            <input type="reset" value=" 重置 " class="button" />
        </div>
    </form>
</div>

<?php include_once "/assets/template/footer.php";?>
</body>
</html>
<iframe style="display:none;" name="ifr"></iframe>
<div id="upload" style="position:absolute;display:none;padding:10px;border:1px solid #CCC;background:#FFF;width:360px;">
    <form id="pre_form" target="ifr" method="POST" action="<?php echo U('Admin/Goods/ajaxUpload');?>" enctype="multipart/form-data">
        图片：<input type="file" name="img" onchange="ajaxUpload();"/><input type="submit" value="上传" />
        <a id="close" href="javascript:void(0);"> [关闭] </a>
    </form>
</div>
<div id="bupload" style="position:absolute;display:none;padding:10px;border:1px solid #CCC;background:#FFF;width:360px;">
    <form id="bpre_form" target="ifr" method="POST" action="<?php echo U('Admin/Goods/ajaxBUpload');?>" enctype="multipart/form-data">
        图片：<input type="file" name="img" onchange="ajaxBUpload();" /><input type="submit" value="上传" />
        <a id="bclose" href="javascript:void(0);"> [关闭] </a>
    </form>
</div>

<script>
    $("#tabbar-div p span").click(function(){
        // 先去掉原选中状态
        $(".tab-front").removeClass("tab-front").addClass("tab-back");
        // 把当前按钮变成选中状态
        $(this).removeClass("tab-back").addClass("tab-front");
        // 当前是第几个按钮
        var i = $(this).index();
        // 先隐藏所有的div
        $(".tabbody-div").hide();
        // 显示相应的div
        $(".tabbody-div").eq(i).show();
    });
    //商品属性展示
    $('#type_id').change(function () {
        var type_id = $(this).val();
         if(type_id>0)
         {
            $.ajax({
                type : "GET",
                url  : "__CONTROLLER__/ajaxGetAttrForm/type_id/"+type_id,
                success : function(data)
                {
                    $('#attrContent').find("tr:gt(0)").remove();
                    $('#attrContent').append(data);
                }
            });
         }
        else
         {
             $('#attrContent').find("tr:gt(0)").remove();
         }
    });

    //克隆
    function addANewAttRow(o)
    {
        // 先取出a标签所在的tr
        var tr = $(o).parent().parent();
        if($(o).html() == "[+]")
        {
            // 复制tr
            var newTr = tr.clone();
            newTr.find("a").html("[-]");
            tr.after(newTr);
        }
        else
            tr.remove();
    }

    $("#close,.gallery").click(function(){
        $("#upload").hide();
    });
    $("#bclose,.basic-info").click(function(){
        $("#bupload").hide();
    });
    $("#selImg").click(function(){
        // 获取按钮的位置
        var p = $(this).position();
        var div = $("#upload");
        div.css({
            "left":p.left+"px",
            "top":p.top+"px",
            "display":""
        });
    });
    //图片按钮
    $("#selBImg").click(function(){
        // 获取按钮的位置
        var p = $(this).position();
        var div = $("#bupload");
        div.css({
            "left":p.left+"px",
            "top":p.top+"px",
            "display":""
        });
    });

    /**********选择图片，关闭上传窗口************/
    function ajaxUpload()
    {
        $('#pre_form').submit();
        $("#upload").hide();
    }
    /**********商品相册，关闭上传窗口************/
    function ajaxBUpload()
    {
        $('#bpre_form').submit();
        $("#bupload").hide();
    }

</script>