<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="{:C('css')}/general.css" rel="stylesheet" type="text/css" />
<style type="text/css">
#header-div {
  background:#278296;
  border-bottom:1px solid #FFF;
}

#logo-div {
  height:50px;
  float:left;
}

#submenu-div {
  height:50px;
}

#submenu-div ul {
  margin:3px 20px 0 0;
  padding:0;
  float:right;
  list-style-type:none;
}

#submenu-div li {
  float:left;
  padding:0 10px;
  margin:3px 0;
  border-right:1px solid #FFF;
}

#submenu-div a:visited, #submenu-div a:link {
  color:#FFF;
  text-decoration:none;
}

#submenu-div a:hover {
  color:#F5C29A;
}

#loading-div {
  clear:right;
  text-align:right;
  display:block;
}

#menu-div {
  background:#80BDCB;
  font-weight:bold;
  height:24px;
  line-height:24px;
}

#menu-div ul {
  margin:0;
  padding:0;
  list-style-type:none;
}

#menu-div li {
  float:left;
  border-right:1px solid #192E32;
  border-left:1px solid #BBDDE5;
}

#menu-div a:visited, #menu-div a:link {
  display:block;
  padding:0 20px;
  text-decoration:none;
  color:#335B64;
  background:#9CCBD6;
}

#menu-div a:hover {
  color:#000;
  background:#80BDCB;
}

#submenu-div a.fix-submenu{
    clear:both;
    margin-left:5px;
    padding:1px 5px;
    background:#DDEEF2;
    color:#278296;
}

#submenu-div a.fix-submenu:hover{
    padding:1px 5px;
    background:#FFF;
    color:#278296;
}

#menu-div li.fix-spacel{
    width:30px;
    border-left:none;
}

#menu-div li.fix-spacer{
    border-right:none;
}
#send_info {
  padding:5px 30px 0 0;
  clear:right;
  text-align:right;
  color:#FF9900;
  width:40%;
  float:right;  
}
</style>
<script>
window.onload=function(){
//定时器每秒调用一次fnDate()
    setInterval(function(){
        fnDate();
    },1000);
}
//js 获取当前时间
function fnDate(){
    var oDiv=document.getElementById("currentTime");
    var date=new Date();
    var year=date.getFullYear();//当前年份
    var month=date.getMonth();//当前月份
    var data=date.getDate();//天
    var hours=date.getHours();//小时
    var minute=date.getMinutes();//分
    var second=date.getSeconds();//秒
    var time=year+"-"+fnW((month+1))+"-"+fnW(data)+" "+fnW(hours)+":"+fnW(minute)+":"+fnW(second);
    oDiv.innerHTML='当前时间:'+time;
}
//补位 当某个字段不是两位数时补0
function fnW(str){
    return str>10?str:'0'+str;
}
</script>
</head>
<body>
<div id="header-div">
    <div id="logo-div" style="bgcolor:#000000;">
        <img src="{:C('img')}/ecshop_logo.gif" alt="跃飞商城" />
    </div>
    <div id="submenu-div">
        <ul>
            <li style="color:#ffffff" id="currentTime">当前时间:<?php echo date('Y-m-d H:i:s');?></li>
            <li style="color: red;font-weight: bold">当前管理员:<?php echo session('username'); ?></li>
            <li><a href="<?php echo getWebsite();?>" target="_blank">查看网店</a></li>
            <li><a href="<?php echo U('Admin/AdminMember/save',array('id'=>$_SESSION['userId']));?>" target="main-frame">个人设置</a></li>
            <li style="border-right:none"><a href="<?php echo U('Admin/Index/index');?>">刷新</a></li>
        </ul>
        <div id="send_info">
            <a href="<?php echo U('Admin/Index/clearCache');?>" target="main-frame" class="fix-submenu">清除缓存文件</a>
            <a href="<?php echo U('Admin/Goods/clearPic');?>" target="main-frame" class="fix-submenu">清除缓存图片</a>
            <a href="<?php echo U("Admin/Manager/logout"); ?>" target="_top" class="fix-submenu">退出</a>
        </div>
    </div>
</div>
<div id="menu-div">
    <ul>
        <li class="fix-spacel">&nbsp;</li>
        <li><a href="<?php echo U("Admin/Index/main"); ?>" target="main-frame">起始页</a></li>
        <li><a href="<?php echo U("Admin/Goods/lst");?>" target="main-frame">商品列表</a></li>
        <li><a href="<?php echo U("Admin/Order/lst");?>" target="main-frame">订单列表</a></li>
        <li><a href="<?php echo U("Admin/Comment/lst");?>" target="main-frame">用户评论</a></li>
        <li><a href="<?php echo U("Admin/User/lst");?>" target="main-frame">会员列表</a></li>
        <li class="fix-spacer">&nbsp;</li>
    </ul>
    <br class="clear" />
</div>
</body>
</html>