<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?php echo C('shopName');?> - 修改广告 </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="{:C('css')}/general.css" rel="stylesheet" type="text/css" />
    <link href="{:C('css')}/main.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="<?php echo C('jq-ui');?>/datetimepicker/jquery.datetimepicker.css"/ >
    <script src="<?php echo C('jq-ui');?>/datetimepicker/jquery.js"></script>
    <script src="<?php echo C('jq-ui');?>/datetimepicker/jquery.datetimepicker.js"></script>
    <script src="<?php echo C('jq-ui');?>/jquery-validation-1.15.0/dist/jquery.validate.js"></script>
    <script src="<?php echo C('js');?>/validate.js"></script>
</head>
<body>
<h1>
    <span class="action-span"><a href="<?php echo U("Admin/Ad/lst") ?>">广告列表</a></span>
    <span class="action-span1"><a href="<?php echo U("Admin/Index/index") ?>"><?php echo C('shopName');?></a></span>
    <span id="search_id" class="action-span1"> - 修改广告 </span>
    <div style="clear:both"></div>
</h1>
<div class="main-div">
    <form method="post" action="<?php echo U("Admin/Ad/save") ?>" id="adForm" enctype="multipart/form-data" >
        <table cellspacing="1" cellpadding="3" width="100%">
            <input type="hidden" id="logo" size="40" name="ad_img" value="<?php echo $data['sm2_logo']?>"/>
            <input type="hidden" name="old_ad_img[]" value="<?php echo $data['sm2_logo']?>"/>
            <input type="hidden" name="old_ad_img[]" value="<?php echo $data['sm1_logo']?>"/>
            <input type="hidden" name="old_ad_img[]" value="<?php echo $data['ad_img']?>"/>
            <input type="hidden"  size="40" name="ad_size" id="ad_size" value="<?php echo $size;?>"/>
            <input type="hidden"  size="40" name="id" value="<?php echo $data['id'];?>"/>
            <tr>
                <td class="label">广告名称</td>
                <td>
                    <input type="text" name="ad_name" maxlength="60" size="60" value="<?php echo $data['ad_name'];?>" />
                </td>
            </tr>
            <tr>
                <td class="label">广告显示位置</td>
                <td>
                    <select name="adpos_id" id="adpos_id">
                        <option value="">请选择</option>
                        <?php foreach ($adPosition as $k=>$v): ?>
                            <option
                                <?php if($v['id'] == $data['adpos_id']):?>
                                    selected = "selected"
                                <?php endif;?>
                                value="<?php echo $v['id'];?>" data-width="<?php echo $v['adpos_width'] ?>" data-height="<?php echo $v['adpos_height'] ?>"><?php echo $v['adpos_name'];?>（<?php echo $v['adpos_width'] ?>*<?php echo $v['adpos_height'] ?>px）</option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            
            <tr>
                <td class="label">广告图片</td>
                <td>
                    <img id="pre_img" src="<?php echo $data['sm1_logo'];?>" style="cursor: pointer" title="可更换"/>
                </td>
            </tr>
            <tr>
                <td class="label">广告链接</td>
                <td>
                    <input type="text" name="ad_url" maxlength="60" size="60" value="<?php echo $data['ad_url'];?>" />
                </td>
            </tr>

            <tr>
                <td class="label">开始时间</td>
                <td>
                    <input type="text" class="datetime" name="start_time" id="start_time" maxlength="60" size="40" value="<?php echo $data['start_time'];?>" />
                </td>
            </tr>
            <tr>
                <td class="label">结束时间</td>
                <td>
                    <input type="text" class="datetime" name="end_time" id="end_time" maxlength="60" size="40" value="<?php echo $data['end_time'];?>" />
                </td>
            </tr>
            <tr>
                <td class="label">是否新窗口打开</td>
                <td>
                    <input type="radio" name="open_new" value="1" <?php if($data['open_new']==1):?>checked="checked"<?php endif;?>/> 是
                    <input type="radio" name="open_new" value="0" <?php if($data['open_new']==0):?>checked="checked"<?php endif;?> /> 否
                </td>
            </tr>
            <tr>
                <td class="label">是否开启</td>
                <td>
                    <input type="radio" name="enabled" value="1" <?php if($data['enabled']==1):?>checked="checked"<?php endif;?> /> 是
                    <input type="radio" name="enabled" value="0" <?php if($data['enabled']==0):?>checked="checked"<?php endif;?> /> 否
                </td>
            </tr>
            <tr>
                <td colspan="2" align="center"><br />
                    <input type="submit" class="button" value=" 确定 " />
                    <input type="reset" class="button" value=" 重置 " />
                </td>
            </tr>
        </table>
    </form>
</div>
<?php include_once "/assets/template/footer.php";?>
</body>
</html>

<!--图片上传 start-->
<iframe style="display:none;" name="ifr"></iframe>
<div id="upload" style="display: none">
    <form id="pre_form" target="ifr" method="POST" action="<?php echo U('Admin/Ad/ajaxUpload');?>" enctype="multipart/form-data">
       <input type="file" name="img" onchange="ajaxUpload();"/>
    </form>
</div>
<!--图片上传 end-->

<script>
    $(function(){
        $('.datetime').datetimepicker({
            lang:'ch', //选择中文
            format:'Y-m-d H:i:s', //格式化日期时间
//            timepicker:false, //去掉时间
//            maxDate:'+1970/01/01',  //最大日期是今天
            yearStart:2015,  //最小年份
        });
        //当点击图片的时候，让它去点击上传按钮，再触发提交表单
        $('#pre_img').click(function () {
            $("#pre_form input[name='img']").click();
        });

        //广告位大小
        $('#adpos_id').change(function () {
            if($(this).val() >0)
            {
                var width = $(this).find("option:selected").data('width');
                var height = $(this).find("option:selected").data('height');
                $('#ad_size').val(width+','+height);
            }
            else
            {
                $('#ad_size').val('');
            }
        });


    });

    function ajaxUpload()
    {
        $('#pre_form').submit();
    }
</script>