<extend name="Layout/gv_user" />

<block name="header_meta">
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>购物车</title>
	<link rel="stylesheet" href="<?php echo C('f-css');?>/base.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/global.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/header.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/cart.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/footer.css" type="text/css">

	<script type="text/javascript" src="<?php echo C('f-js');?>/jquery-1.8.3.min.js"></script>
	<script type="text/javascript" src="<?php echo C('f-js');?>/cart1.js"></script>
</block>

<block name="nav">
	<!-- 顶部导航 start -->
	<div class="topnav">
		<div class="topnav_bd w990 bc">
			<div class="topnav_left">

			</div>
			<div class="topnav_right fr">
				<ul>
					<li>您好，欢迎来到gv！[<a href="<?php echo U('Home/User/login')?>">登录</a>] [<a href="<?php echo U('Home/User/register')?>">免费注册</a>] </li>
					<?php foreach($topNav as $k=>$v):?>
						<li class="line">|</li>
						<li><a href="<?php echo $v['url'];?>" <?php if($v['open_new'] == 1):?>target="_blank" <?php endif;?>><?php echo $v['name']?></a></li>
					<?php endforeach;?>

				</ul>
			</div>
		</div>
	</div>
	<!-- 顶部导航 end -->
</block>


<block name="main">

	<!-- 页面头部 start -->
	<div class="header w990 bc mt15">
		<div class="logo w990">
			<h2 class="fl"><a href="/"><img src="<?php echo C('f-img');?>/logo.png" alt="京西商城"></a></h2>
			<div class="flow fr">
				<ul>
					<li class="cur">1.我的购物车</li>
					<li>2.填写核对订单信息</li>
					<li>3.成功提交订单</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- 页面头部 end -->

	<div style="clear:both;"></div>

	<!-- 主体部分 start -->
	<div class="mycart w990 mt10 bc">
		<h2><span>我的购物车</span></h2>
		<table>
			<thead>
			<tr>
				<th class="col1">商品名称</th>
				<th class="col2">商品信息</th>
				<th class="col3">单价</th>
				<th class="col4">数量</th>
				<th class="col5">小计</th>
				<th class="col6">操作</th>
			</tr>
			</thead>
			<tbody>
			<tr>
				<td class="col1"><a href=""><img src="<?php echo C('f-img');?>/cart_goods1.jpg" alt="" /></a>  <strong><a href="">【1111购物狂欢节】惠JackJones杰克琼斯纯羊毛菱形格</a></strong></td>
				<td class="col2"> <p>颜色：073深红</p> <p>尺码：170/92A/S</p> </td>
				<td class="col3">￥<span>499.00</span></td>
				<td class="col4">
					<a href="javascript:;" class="reduce_num"></a>
					<input type="text" name="amount" value="1" class="amount"/>
					<a href="javascript:;" class="add_num"></a>
				</td>
				<td class="col5">￥<span>499.00</span></td>
				<td class="col6"><a href="">删除</a></td>
			</tr>
			<tr>
				<td class="col1"><a href=""><img src="<?php echo C('f-img');?>/cart_goods2.jpg" alt="" /></a> <strong><a href="">九牧王王正品新款时尚休闲中长款茄克EK01357200</a></strong></td>
				<td class="col2"> <p>颜色：淡蓝色</p> <p>尺码：165/88</p></td>
				<td class="col3">￥<span>1102.00</span></td>
				<td class="col4">
					<a href="javascript:;" class="reduce_num"></a>
					<input type="text" name="amount" value="1" class="amount"/>
					<a href="javascript:;" class="add_num"></a>
				</td>
				<td class="col5">￥<span>1102.00</span></td>
				<td class="col6"><a href="">删除</a></td>
			</tr>
			<tr>
				<td class="col1"><a href=""><img src="<?php echo C('f-img');?>/cart_goods3.jpg" alt="" /></a> <strong><a href="">【1111购物狂欢节】捷王纯手工缝制休闲男鞋大头皮鞋 头层牛</a></strong></td>
				<td class="col2"> <p>颜色：0922红棕现货</p> <p>尺码：40现货</p></td>
				<td class="col3">￥<span>269.00</span></td>
				<td class="col4">
					<a href="javascript:;" class="reduce_num"></a>
					<input type="text" name="amount" value="1" class="amount"/>
					<a href="javascript:;" class="add_num"></a>
				</td>
				<td class="col5">￥<span>269.00</span></td>
				<td class="col6"><a href="">删除</a></td>
			</tr>
			</tbody>
			<tfoot>
			<tr>
				<td colspan="6">购物金额总计： <strong>￥ <span id="total">1870.00</span></strong></td>
			</tr>
			</tfoot>
		</table>
		<div class="cart_btn w990 bc mt10">
			<a href="<?php echo U("Home/Cart/flow2");?>" class="continue">继续购物</a>
			<a href="<?php echo U("Home/Cart/flow2");?>" class="checkout">结 算</a>
		</div>
	</div>
	<!-- 主体部分 end -->

</block>
