<extend name="Layout/gv_user" />

<block name="header_meta">
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>购物车</title>
	<link rel="stylesheet" href="<?php echo C('f-css');?>/base.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/global.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/header.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/cart.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/footer.css" type="text/css">

	<script type="text/javascript" src="<?php echo C('f-js');?>/jquery-1.8.3.min.js"></script>
	<script type="text/javascript" src="<?php echo C('f-js');?>/cart1.js"></script>
</block>

<block name="nav">
	<!-- 顶部导航 start -->
	<div class="topnav">
		<div class="topnav_bd w990 bc">
			<div class="topnav_left">

			</div>
			<div class="topnav_right fr">
				<ul>
					<li>您好，欢迎来到gv！[<a href="<?php echo U('Home/User/login')?>">登录</a>] [<a href="<?php echo U('Home/User/register')?>">免费注册</a>] </li>
					<?php foreach($topNav as $k=>$v):?>
						<li class="line">|</li>
						<li><a href="<?php echo $v['url'];?>" <?php if($v['open_new'] == 1):?>target="_blank" <?php endif;?>><?php echo $v['name']?></a></li>
					<?php endforeach;?>

				</ul>
			</div>
		</div>
	</div>
	<!-- 顶部导航 end -->
</block>


<block name="main">

	<!-- 页面头部 start -->
	<div class="header w990 bc mt15">
		<div class="logo w990">
			<h2 class="fl"><a href="/"><img src="<?php echo C('f-img');?>/logo.png" alt="京西商城"></a></h2>
			<div class="flow fr">
				<ul>
					<li class="cur">1.我的购物车</li>
					<li>2.填写核对订单信息</li>
					<li>3.成功提交订单</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- 页面头部 end -->

	<div style="clear:both;"></div>

	<!-- 主体部分 start -->
	<div class="mycart w990 mt10 bc">
		<h2><span>我的购物车</span></h2>
		<table>
			<thead>
			<tr>
				<th class="col1">商品名称</th>
				<th class="col2">商品信息</th>
				<th class="col3">单价</th>
				<th class="col4">数量</th>
				<th class="col5">小计</th>
				<th class="col6">操作</th>
			</tr>
			</thead>
			<tbody>
			<?php
			$totalPrice = 0;
			foreach ($goods as $k=>$v):?>
			<tr data-goods_id="<?php echo $v['goods_id']; ?>" data-goods_attr="<?php echo $v['goods_attr_id']; ?>">
				<td class="col1"><a href="<?php echo U('Home/goods/detail',array('id'=>$v['goods_id']));?>"><img src="<?php echo $v['sm_logo'];?>" alt="<?php echo $v['goods_name'];?>" /></a>  <strong><a href="<?php echo U('Home/goods/detail',array('id'=>$v['goods_id']));?>"><?php echo $v['goods_name'];?></a></strong></td>
				<td class="col2"> <p><?php echo $v['goods_attr_str'];?></p> </td>
				<td class="col3">￥<span><?php echo $v['shop_price'];?></span></td>
				<td class="col4">
					<a href="javascript:;" class="reduce_num"></a>
					<input type="text" name="amount" value="<?php echo $v['goods_number'];?>" class="amount"/>
					<a href="javascript:;" class="add_num"></a>
				</td>
				<td class="col5">￥
					<span>
						<?php
						$_price = $v['shop_price'] * $v['goods_number'];
						$totalPrice += $_price;
						echo $_price;
						?>
					</span></td>
				<td class="col6"><a href="">删除</a></td>
			</tr>
			<?php endforeach;?>
			</tbody>
			<tfoot>
			<tr>
				<td colspan="6">购物金额总计： <strong>￥ <span id="total"><?php echo $totalPrice;?></span></strong></td>
			</tr>
			</tfoot>
		</table>
		<div class="cart_btn w990 bc mt10">
			<a href="<?php echo U("Home/Index/index");?>" class="continue">继续购物</a>
			<a href="<?php echo U("Home/Cart/flow2");?>" class="checkout">结 算</a>
		</div>
	</div>
	<!-- 主体部分 end -->

	<script>
		//异步更新购物车数量
		function ajaxUpdateCartGoodsNumber(goods_id, goods_attr, goods_number)
		{
			$.ajax({
				type : "POST",
				url : "<?php echo U('Home/Cart/ajaxUpdateCartGoodsNumber'); ?>",
				data:{
					'goods_id':goods_id,
					'goods_attr':goods_attr,
					'goods_number':goods_number
				},
				success : function(result)
				{

				}
			});
		}

	</script>


</block>
