<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?php echo C('shopName');?> - 活动列表 </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="<?php echo C('css');?>/general.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo C('css');?>/main.css" rel="stylesheet" type="text/css" />
</head>
<body>
<h1>
    <span class="action-span"><a href="<?php echo U("Admin/Activity/add")?>">添加活动</a></span>
    <span class="action-span1"><a href="<?php echo U("Admin/Index/index")?>"><?php echo C('shopName');?></a></span>
    <span id="search_id" class="action-span1"> -活动列表 </span>
    <div style="clear:both"></div>
</h1>
<div class="form-div">
    <form action="<?php echo U('Admin/Activity/lst');?>" name="searchForm" method="get">
        <img src="{:C('img')}/icon_search.gif" width="26" height="22" border="0" alt="search" />
        <input type="text" name="keyword" size="50" placeholder="标题|链接" value="<?php echo $_GET['keyword']?>"/>
        <input type="submit" value=" 搜索 " class="button" />
    </form>
</div>
<form method="post" action="" name="listForm">
    <div class="list-div" id="listDiv">
        <table cellpadding="3" cellspacing="1">
            <tr>
                <th>活动id</th>
                <th>活动标题</th>
                <th>商品sn</th>
                <th>链接</th>
                <th>发布时间</th>
                <th>操作</th>
            </tr>
            <?php foreach ($activity as $k=>$v):?>
            <tr>
                <td class="first-cell"><?php echo $v['id'];?></td>
                <td align="center"><?php echo $v['title'];?></td>
                <td align="center"><?php echo $v['goods_sn'];?></td>
                <td align="center"><?php echo $v['link'];?></td>
                <td align="center"><?php echo formatDate($v['add_time']);?></td>
                <td align="center">
                    <a href="<?php echo $v['link'];?>" target="_blank" title="查看">查看</a> |
                    <a href="<?php echo U("Admin/Activity/save",array('id'=>$v['id']))?>" title="编辑">编辑</a> |
                    <a onclick="return confirm('确定要删除吗');" href="<?php echo U("Admin/Activity/delete",array('id'=>$v['id']))?>" title="移除">移除</a>
                </td>
            </tr>
            <?php endforeach;?>
            <tr>
                <td align="center" nowrap="true" colspan="6">
                    <?php echo $page;?>
                </td>
            </tr>
        </table>
    </div>
</form>

<?php include_once "/assets/template/footer.php";?>
</body>
</html>