<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?php echo C('shopName');?> - 文章分类 </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="{:C('css')}/general.css" rel="stylesheet" type="text/css" />
    <link href="{:C('css')}/main.css" rel="stylesheet" type="text/css" />
    <link type="text/css" href="{:C('css')}/jquery.tbltree.css" rel="stylesheet">
    <script src="{:C('js')}/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="{:C('js')}/jquery-ui.min.js"></script>
    <script type="text/javascript" src="{:C('js')}/jquery.cookie.js"></script>
    <script type="text/javascript" src="{:C('js')}/jquery.tbltree.js"></script>
    <script src="{:C('js')}/scale.fix.js"></script>
    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script>
        $(function() {
            $( "#article_cat" ).tbltree({
                treeColumn: 0,
                saveState: true
            });
        });
    </script>
</head>
<body>
<h1>
    <span class="action-span"><a href="<?php echo U("Admin/ArticleCat/add")?>">添加文章分类</a></span>
    <span class="action-span1"><a href="<?php echo U("Admin/Index/index")?>"><?php echo C('shopName');?></a></span>
    <span id="search_id" class="action-span1"> -文章分类 </span>
    <div style="clear:both"></div>
</h1>
<form method="post" action="" name="listForm">
    <div class="list-div" id="listDiv">
        <table cellpadding="3" cellspacing="1" id="article_cat">
            <tr>
                <th>文章分类名称</th>
                <th>分类类型</th>
                <th>描述</th>
                <th>排序</th>
                <th>操作</th>
            </tr>
            <?php foreach ($article_cat_data as $k => $v):?>
            <tr row-id="<?php echo $v['cat_id'];?>" <?php if($v['parent_id']):?> parent-id="<?php echo $v['parent_id'] ?>" <?php endif;?> >
                <td class="first-cell">
                   <?php echo $v['cat_name'];?>
                </td>
                <td align="center">
                    <?php echo $cat_type[$v['cat_type']]?>
                </td>
                <td align="center"><?php echo $v['cat_desc']?></td>
                <td align="center"><?php echo $v['sort_order']?></td>
                <td align="center">
                    <a href="<?php echo U("Admin/ArticleCat/save/",array("cat_id"=>$v['cat_id']))?>" title="编辑">编辑</a>
                    <?php if($v['cat_type']==1 || $v['cat_type']==5 ):?>
                    | <a onclick="return confirm('确定要删除吗,删除分类的同时会删除该分类下的所有文章');" href="<?php echo U("Admin/ArticleCat/delete/",array("cat_id"=>$v['cat_id']))?>" title="移除">移除</a>
                    <?php endif;?>
                </td>
            </tr>
            <?php endforeach;?>
        </table>
    </div>
</form>

<?php include_once "/assets/template/footer.php";?>
</body>
</html>