<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo C('shopName');?> - 导航栏列表 </title>
    <link href="{:C('css')}/general.css" rel="stylesheet" type="text/css" />
    <link href="{:C('css')}/main.css" rel="stylesheet" type="text/css" />
</head>
<body>
<h1>
    <span class="action-span"><a href="<?php echo U("Admin/Nav/add")?>">添加导航栏</a></span>
    <span class="action-span1"><a href="<?php echo U("Admin/Index/index")?>"><?php echo C('shopName');?></a></span>
    <span id="search_id" class="action-span1"> -导航栏列表 </span>
    <div style="clear:both"></div>
</h1>
<div class="form-div">
    <form action="" name="searchForm">
        <img src="{:C('img')}/icon_search.gif" width="26" height="22" border="0" alt="search" />
        <input type="text" name="brand_name" size="15" />
        <input type="submit" value=" 搜索 " class="button" />
    </form>
</div>
<form method="post" action="" name="listForm">
    <div class="list-div" id="listDiv">
        <table cellpadding="3" cellspacing="1">
            <tr>
                <th>编号</th>
                <th>导航栏名称</th>
                <th>是否显示</th>
                <th>是否新窗口</th>
                <th>排序</th>
                <th>位置</th>
                <th>操作</th>
            </tr>
            <?php foreach ($nav as $k=>$v):?>
                <tr>
                    <td>
                        <?php echo $v["id"]?>
                    </td>
                    <td>
                        <?php echo $v["name"]?>
                    </td>
                    <td align="center">

                        <?php if($v["is_show"] == 1):?>
                            <img src="<?php echo C('img')?>/yes.gif" alt="是">
                        <?php else:?>
                            <img src="<?php echo C('img')?>/no.gif" alt="否">
                        <?php endif;?>
                    </td>
                    <td align="center">
                        <?php if($v['open_new'] == 1):?>
                            <img src="<?php echo C('img')?>/yes.gif" alt="是">
                        <?php else:?>
                            <img src="<?php echo C('img')?>/no.gif" alt="否">
                        <?php endif;?>
                    </td>
                    <td align="center">
                        <?php echo $v['view_order']?>
                    </td>
                    <td align="center"><?php echo $position[$v['position']];?></td>
                    <td align="center">
                        <a href="<?php echo U("Admin/Nav/save",array('id'=>$v['id']))?>" title="编辑">编辑</a> |
                        <a onclick="return confirm('确定要删除吗');" href="<?php echo U("Admin/Nav/delete",array('id'=>$v['id']))?>" title="删除">移除</a>
                    </td>
                </tr>
            <?php endforeach;?>
            <tr>
                <td align="center" nowrap="true" colspan="7">
                    <?php echo $page;?>
                </td>
            </tr>
        </table>
    </div>
</form>

<?php include_once "/assets/template/footer.php";?>
</body>
</html>