<extend name="Layout/gv_user" />
<block name="header_meta">
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>成功提交订单</title>
	<link rel="stylesheet" href="<?php echo C('f-css');?>/base.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/global.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/header.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/success.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/footer.css" type="text/css">
</block>

<block name="nav">
	<!-- 顶部导航 start -->
	<div class="topnav">
		<div class="topnav_bd w990 bc">
			<div class="topnav_left">

			</div>
			<div class="topnav_right fr">
				<ul>
					<li>您好，<?php $user_email = cookie('user_email'); if(isset($user_email) || session("?user_email")):?><font color="red"><?php if($user_email){echo $user_email;}else{echo session('user_email'); }?></font><?php endif;?> 欢迎来到gv！
						<?php if(isset($user_email) || session("?user_email")):?>
							[<a href="<?php echo U('Home/User/logout')?>">退出</a>]
						<?php else:?>
							[<a href="<?php echo U('Home/User/login')?>">登录</a>]
																			   [<a href="<?php echo U('Home/User/register')?>">免费注册</a>]
						<?php endif;?>
					</li>
					<?php foreach($topNav as $k=>$v):?>
						<li class="line">|</li>
						<li><a href="<?php echo $v['url'];?>" <?php if($v['open_new'] == 1):?>target="_blank" <?php endif;?>><?php echo $v['name']?></a></li>
					<?php endforeach;?>

				</ul>
			</div>
		</div>
	</div>
	<!-- 顶部导航 end -->
</block>


<block name="main">
	<!-- 页面头部 start -->
	<div class="header w990 bc mt15">
		<div class="logo w990">
			<h2 class="fl"><a href="/"><img src="<?php echo C('f-img');?>/logo.png" alt="京西商城"></a></h2>
			<div class="flow fr flow3">
				<ul>
					<li>1.我的购物车</li>
					<li>2.填写核对订单信息</li>
					<li class="cur">3.成功提交订单</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- 页面头部 end -->

	<div style="clear:both;"></div>

	<!-- 主体部分 start -->
	<div class="success w990 bc mt15">
		<div class="success_hd">
			<h2>订单提交成功</h2>
		</div>
		<div class="success_bd">
			<p><span></span>订单提交成功，我们将及时为您处理</p>
			<?php echo $goPay; ?>
			<p class="message">完成支付后，你可以 <a href="">查看订单状态</a>  <a href="">继续购物</a> <a href="">问题反馈</a></p>
		</div>
	</div>
	<!-- 主体部分 end -->
</block>