<extend name="Layout/gv_user" />

<block name="header_meta">
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>订单结算页-<?php echo C('company');?></title>
	<link rel="stylesheet" href="<?php echo C('f-css');?>/base.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/global.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/header.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/fillin.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/footer.css" type="text/css">

	<script type="text/javascript" src="<?php echo C('f-js');?>/jquery-1.8.3.min.js"></script>
	<script type="text/javascript" src="<?php echo C('f-js');?>/cart2.js"></script>
</block>

<block name="nav">
	<!-- 顶部导航 start -->
	<div class="topnav">
		<div class="topnav_bd w990 bc">
			<div class="topnav_left">

			</div>
			<div class="topnav_right fr">
				<ul>
					<li>您好，<?php $user_email = cookie('user_email'); if(isset($user_email) || session("?user_email")):?><font color="red"><?php if($user_email){echo $user_email;}else{echo session('user_email'); }?></font><?php endif;?> 欢迎来到gv！
						<?php if(isset($user_email) || session("?user_email")):?>
							[<a href="<?php echo U('Home/User/logout')?>">退出</a>]
						<?php else:?>
							[<a href="<?php echo U('Home/User/login')?>">登录</a>]
							[<a href="<?php echo U('Home/User/register')?>">免费注册</a>]
						<?php endif;?>
					</li>
					<?php foreach($topNav as $k=>$v):?>
						<li class="line">|</li>
						<li><a href="<?php echo $v['url'];?>" <?php if($v['open_new'] == 1):?>target="_blank" <?php endif;?>><?php echo $v['name']?></a></li>
					<?php endforeach;?>

				</ul>
			</div>
		</div>
	</div>
	<!-- 顶部导航 end -->
</block>


<block name="main">

	<!-- 页面头部 start -->
	<div class="header w990 bc mt15">
		<div class="logo w990">
			<h2 class="fl"><a href="/"><img src="<?php echo C('f-img');?>/logo.png" alt="京西商城"></a></h2>
			<div class="flow fr flow2">
				<ul>
					<li>1.我的购物车</li>
					<li class="cur">2.填写核对订单信息</li>
					<li>3.成功提交订单</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- 页面头部 end -->

	<div style="clear:both;"></div>

	<!-- 主体部分 start -->
	<div class="fillin w990 bc mt15">
		<div class="fillin_hd">
			<h2>填写并核对订单信息</h2>
		</div>
		<form method="post" action="<?php echo U('Home/Order/flow2');?>" id="order_form">
		<div class="fillin_bd">
			<!-- 收货人信息  start-->
			<div class="address">
				<h3>收货人信息 <a href="<?php echo U('Home/Address/add');?>" id="address_modify">[使用新地址]</a></h3>
				<div class="address_select">
					<ul>
						<?php foreach ($userAddressInfo as $k=>$v):?>
						<li>
							<input type="radio" name="address_id" <?php if($v['is_default'] == 1):?>checked="checked"<?php endif;?> value="<?php echo $v['id'];?>" data-consignee="<?php echo $v['consignee'];?>" data-address="<?php echo $v['address'];?>" data-tel="<?php echo $v['tel'];?>"/><?php echo $v['consignee'];?>　<?php echo $v['address'];?>　<?php echo $v['tel'];?>
							<?php if($v['is_default'] == 0):?><a href="<?php echo U('Home/Address/setDefault',array('id'=>$v['id']));?>">设为默认地址</a><?php endif;?>
							<a href="<?php echo U('Home/Address/save',array('id'=>$v['id']));?>">编辑</a>
							<a onclick="return confirm('确定要删除吗');"  href="<?php echo U('Home/Address/delete',array('id'=>$v['id']));?>">删除</a>
						</li>
						<?php endforeach;?>
					</ul>
				</div>
			</div>
			<!-- 收货人信息  end-->

			<!-- 配送方式 start -->
			<div class="delivery">
				<h3>配送方式</h3>
				<div class="delivery_select">
					<table>
						<tr>
							<td>
								由商家选择合作快递为您配送（配送时间:如有发货疑问请咨询客服）
							</td>
							<td>每张订单不满100.00元,运费10.00元，超过100.00元免邮</td>
						</tr>
					</table>
				</div>
			</div>
			<!-- 配送方式 end -->

			<!-- 支付方式  start-->
			<div class="pay">
				<h3>支付方式</h3>
				<div class="pay_select">
					<table>
						<?php foreach ($payment as $k=>$v):?>
						<tr>
							<td class="col1"><input type="radio" name="pay_id" value="<?php echo $v['id']?>"/><?php echo $v['pay_name']?></td>
							<td class="col2"><?php echo $v['pay_desc']?></td>
						</tr>
						<?php endforeach;?>
					</table>
				</div>
			</div>
			<!-- 支付方式  end-->

			<!-- 发票信息 start-->
			<div class="receipt">
				<h3>发票信息</h3>

				<div class="receipt_select">
						<ul>
							<li>
								<label for="">温馨提示:开发票需收取发票费用按商品总金额的6%收取,不开发票可以开收据</label>
							</li>
							<li>
								<label for="">发票类型：</label>
								<input type="radio" name="invoice_type" checked="checked" value="普通发票"/>普通发票
								<input type="radio" name="invoice_type" value="增值税发票" />增值税发票
							</li>
							<li>
								<label for="">发票抬头：</label>
								<input type="radio" name="invoice_header" checked="checked" class="personal" value="个人"/>个人
								<input type="radio" name="invoice_header" class="company" value="单位"/>单位
								<input type="text" class="txt company_input" disabled="disabled" name="invoice_company" placeholder="请输入公司全称" />
							</li>
							<li>
								<label for="">发票内容：</label>
								<input type="radio" name="invoice_content" checked="checked" value="不开发票" />不开发票
								<input type="radio" name="invoice_content" value="明细" />明细
							</li>
						</ul>
				</div>
			</div>
			<!-- 发票信息 end-->

			<!-- 商品清单 start -->
			<div class="goods">
				<h3>送货清单 <span><a href="<?php echo U('Home/Cart/index');?>">[修改购物车]</a></span></h3>
				<table>
					<thead>
					<tr>
						<th class="col1">商品</th>
						<th class="col2">规格</th>
						<th class="col3">价格</th>
						<th class="col4">数量</th>
						<th class="col5">小计</th>
					</tr>
					</thead>
					<tbody>
					<?php
					$totalPrice = 0;
					$totalGoodsNum = 0;
					foreach ($goods as $k=>$v):
					?>
					<tr>
						<td class="col1"><a href="<?php echo U('Home/goods/detail',array('id'=>$v['goods_id']));?>"><img src="<?php echo $v['sm_logo'];?>" alt="<?php echo $v['goods_name'];?>" /></a>  <strong><a href="<?php echo U('Home/goods/detail',array('id'=>$v['goods_id']));?>"><?php echo $v['goods_name'];?></a></strong></td>
						<td class="col2"> <p><?php echo $v['goods_attr_str'];?></p> </td>
						<td class="col3">￥<?php echo $v['shop_price'];?></td>
						<td class="col4">
							<?php
							$totalGoodsNum += $v['goods_number'];
							echo $v['goods_number'];
							?>
						</td>
						<td class="col5">
							<span>￥
								<?php
								$_price = $v['shop_price'] * $v['goods_number'];
								$totalPrice += $_price;
								echo sprintf("%.2f",$_price);
								?>
							</span>
						</td>
					</tr>
					<?php endforeach;?>
					</tbody>
					<tfoot>
					<tr>
						<td colspan="5">
							<ul>
								<li>
									<span><?php echo $totalGoodsNum;?> 件商品，总商品金额：</span>
									<em>￥<?php echo sprintf("%.2f",$totalPrice);?></em>
								</li>
								<li>
									<span>运费：</span>
									<em>￥<?php echo  $fee = $totalPrice>100?0:10; ?></em>
								</li>
							</ul>
						</td>
					</tr>
					<tr>
						<td colspan="5" class="consignee">
<!--							寄送至：xx：张三 137****3587-->
						</td>
					</tr>
					</tfoot>
				</table>
			</div>
			<!-- 商品清单 end -->

		</div>

		<div class="fillin_ft">
			<a href="javascript:void(0)" onclick="$('#order_form').submit();"><span>提交订单</span></a>
			<p>应付总额：<strong>￥<?php echo sprintf("%.2f",$totalPrice+$fee);?></strong></p>

		</div>

			<input type="hidden" name="total_price" value="<?php echo sprintf("%.2f",$totalPrice+$fee);?>"/>
			<input type="hidden" name="postage" value="<?php echo  $fee; ?>"/>
			<input type="hidden" name="goods_number" value="<?php echo $totalGoodsNum;?>"/>
		</form>
	</div>
	<!-- 主体部分 end -->
</block>
