<extend name="Layout/gv" />

<block name="header_meta">
	<title>订单页面</title>
	<link rel="stylesheet" href="<?php echo C('f-css')?>/base.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css')?>/global.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css')?>/header.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css')?>/home.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css')?>/order.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css')?>/bottomnav.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css')?>/footer.css" type="text/css">

	<script type="text/javascript" src="<?php echo C('f-js')?>/jquery-1.8.3.min.js"></script>
	<script type="text/javascript" src="<?php echo C('f-js')?>/header.js"></script>
	<script type="text/javascript" src="<?php echo C('f-js')?>/home.js"></script>
</block>

<block name="main">
	<!-- 页面主体 start -->
	<div class="main w1210 bc mt10">
		<div class="crumb w1210">
			<h2><strong><?php echo C('userCenter');?></strong><span>> 我的订单</span></h2>
		</div>

		<!-- 左侧导航菜单 start -->
		<?php include "/App/Home/View/Layout/user_left.phtml";?>
		<!-- 左侧导航菜单 end -->

		<!-- 右侧内容区域 start -->
		<div class="content fl ml10">
			<div class="order_hd">
				<h3>我的订单</h3>
				<dl>
					<dt>便利提醒：</dt>
					<dd>待付款（0）</dd>
					<dd>待确认收货（0）</dd>
					<dd>待自提（0）</dd>
				</dl>

				<dl>
					<dt>特色服务：</dt>
					<dd><a href="">我的预约</a></dd>
					<dd><a href="">夺宝箱</a></dd>
				</dl>
			</div>

			<?php
			foreach($orderInfo as $k=>$v):?>
			<div class="order_bd mt10">

				<table class="orders">
					<thead>
					<tr>
						<th colspan="8" style="text-align: left;padding-left: 10px;"><?php echo formatDate($v['add_time']);?> 　订单号：<?php echo $v['order_sn'];?> 　跃飞商城</th>
					</tr>
					</thead>
					<tbody>
					<?php foreach ($v['goods'] as $k1=>$v1):?>
					<tr>
						<td width="10%"><a href="<?php echo U('Home/Goods/detail',array('id'=>$v1['goods_id']));?>" target="_blank"><img src="<?php echo $v1['goods_logo'];?>" alt="" /></a></td>
						<td width="35%" class="goods_name"><a href="<?php echo U('Home/Goods/detail',array('id'=>$v1['goods_id']));?>" target="_blank"><?php echo $v1['goods_name'];?></a></td>
						<td width="5%">x<?php echo $v1['goods_number'];?></td>
						<td width="10%">申请售后</td>
						<?php if($k1==0):?>
						<td width="10%" rowspan="<?php echo count($v['goods'])?>"><?php echo $v['consignee'];?></td>
						<td width="10%" rowspan="<?php echo count($v['goods'])?>">
							总额 ¥<?php echo $v['total_price'];?><br/>
							在线支付
						</td>
						<td width="10%" rowspan="<?php echo count($v['goods'])?>">订单详情</td>
						<td width="10%" rowspan="<?php echo count($v['goods'])?>"><a href="">立即购买</a></td>
						<?php endif;?>
					</tr>
					<?php endforeach;?>
					</tbody>
				</table>
			</div>
			<?php endforeach;?>
		</div>
		<!-- 右侧内容区域 end -->
	</div>
	<!-- 页面主体 end-->
</block>