<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo C('shopName');?> - 修改广告位 </title>
    <link href="{:C('css')}/general.css" rel="stylesheet" type="text/css" />
    <link href="{:C('css')}/main.css" rel="stylesheet" type="text/css" />
</head>
<body>
<h1>
    <span class="action-span"><a href="<?php echo U("Admin/AdPosition/lst") ?>">广告位列表</a></span>
    <span class="action-span1"><a href="<?php echo U("Admin/Index/index") ?>"><?php echo C('shopName');?></a></span>
    <span id="search_id" class="action-span1"> - 修改广告位 </span>
    <div style="clear:both"></div>
</h1>
<div class="main-div">
    <form method="post" action="<?php echo U("Admin/AdPosition/save") ?>">
        <table cellspacing="1" cellpadding="3" width="100%">
            <input type="hidden" name="id" value="<?php echo $data['id']?>">
            <tr>
                <td class="label">广告位名称</td>
                <td>
                    <input type="text" name="adpos_name" maxlength="60" value="<?php echo $data['adpos_name']?>" />
                    <span class="require-field">*</span>
                </td>
            </tr>
            <tr>
                <td class="label">广告位高度</td>
                <td>
                    <input type="text" name="adpos_width" maxlength="255" size="10" value="<?php  echo $data['adpos_width']?>" />px
                </td>
            </tr>
            <tr>
                <td class="label">广告位宽度</td>
                <td>
                    <input type="text" name="adpos_height" maxlength="4" size="10" value="<?php echo  $data['adpos_height']?>" />px
                </td>
            </tr>

            <tr>
                <td colspan="2" align="center"><br />
                    <input type="submit" class="button" value=" 确定 " />
                    <input type="reset" class="button" value=" 重置 " />
                </td>
            </tr>
        </table>
    </form>
</div>
<?php include_once "/assets/template/footer.php";?>
</body>
</html>