<extend name="Layout/gv" />

<block name="header_meta">
	<title>用户中心- <?php echo C('company');?></title>
	<link rel="stylesheet" href="<?php echo C('f-css')?>/base.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css')?>/global.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css')?>/header.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css')?>/home.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css')?>/user.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css')?>/bottomnav.css" type="text/css">
	<link rel="stylesheet" href="<?php echo C('f-css')?>/footer.css" type="text/css">

	<script type="text/javascript" src="<?php echo C('f-js')?>/jquery-1.8.3.min.js"></script>
	<script type="text/javascript" src="<?php echo C('f-js')?>/header.js"></script>
	<script type="text/javascript" src="<?php echo C('f-js')?>/home.js"></script>
</block>

<block name="main">
	<!-- 页面主体 start -->
	<div class="main w1210 bc mt10">
		<div class="crumb w1210">
			<h2><strong><?php echo C('userCenter');?></strong><span>> 个人信息</span></h2>
		</div>

		<!-- 左侧导航菜单 start -->
		<?php include "/App/Home/View/Layout/user_left.phtml";?>
		<!-- 左侧导航菜单 end -->

		<!-- 右侧内容区域 start -->
		<div class="content fl ml10">
			<div class="user_hd">
				<h3>个人信息</h3>
			</div>

			<div class="user_bd mt10">
				<form action="<?php echo U('Home/User/save');?>" method="post">
					<input type="hidden" name="user_id" value="<?php echo session('user_id');?>">
					<ul>
						<li>
							<label for="">用户名：</label>
							<input type="text" class="txt" name="username" value="<?php echo $user['username']?>" />
						</li>
						<li>
							<label for="">邮箱：</label>
							<input type="text" class="txt" name="email" value="<?php echo $user['email'];?>" readonly />
						</li>
						<li>
							<label for="">手机号码：</label>
							<input type="text" class="txt"  name="phone_number" value="<?php echo $user['phone_number'];?>" />
						</li>
						<li>
							<label for="">&nbsp;</label>
							<input type="submit" value="修改" class="sbtn" />
						</li>
					</ul>
				</form>
			</div>
		</div>
		<!-- 右侧内容区域 end -->
	</div>
	<!-- 页面主体 end-->
</block>