<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?php echo C('shopName');?> - 属性列表 </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="{:C('css')}/general.css" rel="stylesheet" type="text/css" />
    <link href="{:C('css')}/main.css" rel="stylesheet" type="text/css" />
</head>
<body>
<h1>
    <span class="action-span"><a href="<?php echo U("Admin/Attribute/add",array('type_id'=>$_GET['type_id']))?>">添加属性</a></span>
    <span class="action-span1"><a href="<?php echo U("Admin/Index/index")?>"><?php echo C('shopName');?></a></span>
    <span id="search_id" class="action-span1"> -属性列表 </span>
    <div style="clear:both"></div>
</h1>
<div class="form-div">
        <img src="{:C('img')}/icon_search.gif" width="26" height="22" border="0" alt="search" />
        按商品类型显示:
        <select name="type_id" onchange="search(this.value);">
            <option value="0">所有商品类型</option>
            <?php foreach ($goodsType as $k=>$v): ?>
                <option
                    <?php if($_GET['type_id'] == $v['id']):?>
                        selected = "selected"
                    <?php endif;?>
                    value="<?php echo $v['id'];?>"><?php echo $v['type_name'];?></option>
            <?php endforeach; ?>
        </select>
       <script>
           function search(id)
           {
               window.location.href = "__CONTROLLER__/lst/type_id/"+id;
           }
       </script>
</div>
<form method="post" action="" name="listForm">
    <div class="list-div" id="listDiv">
        <table cellpadding="3" cellspacing="1">
            <tr>
                <th>属性名称</th>
                <th>所属商品类型</th>
                <th>属性类型</th>
                <th>属性可选的值</th>
                <th>操作</th>
            </tr>
            <?php foreach ($attributeData as $k=>$v):?>
            <tr>
                <td class="first-cell">
                    <?php echo $v['attr_name'];?>
                </td>
                <td align="center">
                    <?php echo $goodsTypeData[$v['goods_type_id']]; ?>
                </td>
                <td align="center">
                    <?php if($v['attr_type']==0):?>
                        唯一属性
                        <?php elseif($v['attr_type']==1):?>
                        单选属性
                    <?php endif;?>
                </td>
                <td align="center"><?php echo $v['attr_value'];?></td>
                <td align="center">
                    <a href="<?php echo U('Admin/Attribute/save',array('id'=>$v['id']));?>" title="编辑">编辑</a> |
                    <a href="<?php echo U('Admin/Attribute/delete',array('id'=>$v['id']));?>" title="删除">移除</a>
                </td>
            </tr>
            <?php endforeach;?>
        </table>
    </div>
</form>

<?php include_once "/assets/template/footer.php";?>
</body>
</html>