<extend name="Layout/gv" />
<block name="header_meta">
    <title>帮助中心 - <?php echo C('company');?></title>
    <link rel="stylesheet" href="<?php echo C('f-css');?>/base.css" type="text/css">
    <link rel="stylesheet" href="<?php echo C('f-css');?>/global.css" type="text/css">
    <link rel="stylesheet" href="<?php echo C('f-css');?>/header.css" type="text/css">
    <link rel="stylesheet" href="<?php echo C('f-css');?>/home.css" type="text/css">
    <link rel="stylesheet" href="<?php echo C('f-css');?>/address.css" type="text/css">
    <link rel="stylesheet" href="<?php echo C('f-css');?>/bottomnav.css" type="text/css">
    <link rel="stylesheet" href="<?php echo C('f-css');?>/footer.css" type="text/css">
    <script type="text/javascript" src="<?php echo C('f-js');?>/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="<?php echo C('f-js');?>/header.js"></script>
    <script type="text/javascript" src="<?php echo C('f-js');?>/home.js"></script>
</block>

<block name="main">
    <!-- 页面主体 start -->
    <div class="main w1210 bc mt10">
        <div class="crumb w1210">
            <a class="fst" href="<?php echo  getWebsite();?>" title="首页">首页</a>
            <?php foreach ( $articleCat as $k=>$v):?>
            <span>&gt;</span>
            <a href="javascript:void (0);"><?php echo $v['cat_name'];?></a>
            <?php endforeach;?>
            <span>&gt;</span>
            <?php echo $article['title']?>
        </div>

        <!-- 左侧导航菜单 start -->

        <div class="menu left-nav fl">
            <h2>帮助中心</h2>
            <div class="nav-con">
                <?php foreach ($helpInfo as $k=>$v):?>
                <dl>
                    <dt><em class="<?php if($k==0):?>on<?php endif;?>"></em><span <?php if($k==0):?> class="spcli"<?php endif;?>><?php echo $v['cat_name']?></span></dt>
                    <dd <?php if($k!=0):?>class="hide"<?php endif;?>>
                        <?php foreach ($v['article'] as $k1=>$v1):?>
                        <a href="<?php echo U('Home/Help/lst',array('id'=>$v1['article_id']));?>" <?php if(isCurrent(U('Home/Help/lst',array('id'=>$v1['article_id'])))):?>class="on"<?php endif;?> ><?php echo $v1['title']?></a>
                        <?php endforeach;?>
                    </dd>
                </dl>
               <?php endforeach;?>
            </div>
        </div>
        <!-- 左侧导航菜单 end -->

        <!-- 右侧内容区域 start -->
        <div class="content fl ml10">
            <div class="search-frame">
                <div class="h-search">
                    <div class="search-hot-pro">
                        <span>热门问题：</span>
                        <a href="#">付款</a>
                        <a href="#">发票</a>
                        <a href="#">配送</a>
                        <a href="#">维修</a>
                        <a href="#">邮箱</a>
                        <div class="h-search-box">
                            <span></span>
                            <input type="text" name="keyword" value="">
                            <a href="#" name="helpCenter_search_button_p01"></a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="address_hd">
                <h3><?php echo $article['title']?></h3>
                <dl>
                    <dt></dt>
                    <dd><?php echo htmlspecialchars_decode($article['content'])?></dd>
                </dl>
            </div>

        </div>
        <!-- 右侧内容区域 end -->
    </div>
    <!-- 页面主体 end-->
</block>
