<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?php echo C('shopName');?> - 修改<?php echo $payment['pay_name']?>支付 </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="{:C('css')}/general.css" rel="stylesheet" type="text/css" />
    <link href="{:C('css')}/main.css" rel="stylesheet" type="text/css" />
</head>
<body>
<h1>
    <span class="action-span"><a href="<?php echo U("Admin/Payment/lst") ?>">支付方式</a></span>
    <span class="action-span1"><a href="<?php echo U("Admin/Index/index") ?>"><?php echo C('shopName');?></a></span>
    <span id="search_id" class="action-span1"> - 修改<?php echo $payment['pay_name']?>支付 </span>
    <div style="clear:both"></div>
</h1>
<div class="main-div">
    <form method="post" action="<?php echo U("Admin/Payment/save",array('pay_code'=>$payment['pay_code'])) ?>"enctype="multipart/form-data" >
        <table cellspacing="1" cellpadding="3" width="100%">
            <input type="hidden" name="id" value="<?php echo $payment['id']?>"/>
            <tr>
                <td class="label">接口类型</td>
                <td>
                    网站即时到帐交易接口
                </td>
            </tr>
            <tr>
                <td class="label">支付方式名称</td>
                <td>
                    <input type="text" name="pay_name" maxlength="60" value="<?php echo $payment['pay_name']?>" readonly/>
                </td>
            </tr>
            <tr>
                <td class="label">支付方式描述</td>
                <td>
                    <textarea  name="pay_desc" cols="60" rows="4"  ><?php echo $payment['pay_desc']?></textarea>
                </td>
            </tr>
            <tr>
                <td class="label">合作身份者ID，签约账号</td>
                <td>
                    <input type="text" name="pay_config[partner]" maxlength="16" value="<?php echo $payment['pay_config']['partner']?>" />
                    <span class="notice-span" style="display:block">合作身份者ID，签约账号，以2088开头由16位纯数字组成的字符串，查看地址：https://b.alipay.com/order/pidAndKey.htm</span>
                </td>
            </tr>
            <tr>
                <td class="label">收款支付宝账号</td>
                <td>
                    <input type="text" name="pay_config[seller_id]" maxlength="16" value="<?php echo $payment['pay_config']['seller_id']?>" />
                    <span class="notice-span" style="display:block">收款支付宝账号，以2088开头由16位纯数字组成的字符串，一般情况下收款账号就是签约账号</span>
                </td>
            </tr>
            <tr>
                <td class="label">MD5密钥，安全检验码</td>
                <td>
                    <input type="text" name="pay_config[key]" maxlength="32" size="35" value="<?php echo $payment['pay_config']['key']?>" />
                    <span class="notice-span" style="display:block">MD5密钥，安全检验码，由数字和字母组成的32位字符串，查看地址：https://b.alipay.com/order/pidAndKey.htm</span>
                </td>
            </tr>
            <tr>
                <td class="label">服务器异步通知页面路径</td>
                <td>
                    <input type="text" name="pay_config[notify_url]" maxlength="100" size="100" value="<?php echo $payment['pay_config']['notify_url']?>" />
                    <span class="notice-span" style="display:block">服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问</span>
                </td>
            </tr>
            <tr>
                <td class="label">页面跳转同步通知页面路径</td>
                <td>
                    <input type="text" name="pay_config[return_url]" maxlength="100" size="100" value="<?php echo $payment['pay_config']['return_url']?>" />
                    <span class="notice-span" style="display:block">页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问</span>
                </td>
            </tr>
            <tr>
                <td class="label">访问模式</td>
                <td>
                    <input type="radio" name="pay_config[transport]" value="http" <?php if($payment['pay_config']['transport'] == 'http'):?>checked="checked"<?php endif;?>/>http
                    <input type="radio" name="pay_config[transport]" value="https" <?php if($payment['pay_config']['transport'] == 'https'):?>checked="checked"<?php endif;?>/>https
                    <span class="notice-span" style="display:block">访问模式,根据自己的服务器是否支持ssl访问，若支持请选择https；若不支持请选择http</span>
                </td>
            </tr>
            <tr>
                <td class="label">表单提交方式</td>
                <td>
                    <input type="radio" name="pay_config[method]" value="get" <?php if($payment['pay_config']['method'] == 'get'):?>checked="checked"<?php endif;?>/>get
                    <input type="radio" name="pay_config[method]" value="post" <?php if($payment['pay_config']['method'] == 'post'):?>checked="checked"<?php endif;?>/>post
                    <span class="notice-span" style="display:block">支付跳转时使用get还是post提交到支付宝网关</span>
                </td>
            </tr>
            <tr>
                <td class="label">是否开启</td>
                <td>
                    <input type="radio" name="enabled" value="1" <?php if($payment['enabled'] == 1):?>checked="checked"<?php endif;?>/>开启
                    <input type="radio" name="enabled" value="0" <?php if($payment['enabled'] == 0):?>checked="checked"<?php endif;?>/>关闭
                </td>
            </tr>
            <tr>
                <td class="label">排序</td>
                <td>
                    <input type="text" name="pay_order" maxlength="60" value="<?php echo $payment['pay_order']?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" align="center"><br />
                    <input type="submit" class="button" value=" 确定 " />
                    <input type="reset" class="button" value=" 重置 " />
                </td>
            </tr>
        </table>
    </form>
</div>
<?php include_once "/assets/template/footer.php";?>
</body>
</html>