<!-- $Id: category_info.htm 16752 2009-10-20 09:59:38Z wangleisvn $ -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>ECSHOP 管理中心 - 修改短信 </title>
<meta name="robots" content="noindex, nofollow">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="{:C('css')}/general.css" rel="stylesheet" type="text/css" />
<link href="{:C('css')}/main.css" rel="stylesheet" type="text/css" />
</head>
<body>
<h1>
    <span class="action-span"><a href="<?php echo U("Admin/Sms/lst") ?>">短信列表</a></span>
    <span class="action-span1"><a href="<?php echo U("Admin/Index/index") ?>"><?php echo C('shopName');?> </a></span>
    <span id="search_id" class="action-span1"> - 修改短信 </span>
    <div style="clear:both"></div>
</h1>
<div class="main-div">
    <form action="<?php echo U("Admin/Sms/save")?>" method="post" name="sms" >
        <table width="100%" id="general-table">
            <tr>
                <td class="label"><?php echo $fieldName["ordernumber"]?>:</td>
                <td>
                    <input type='text' name='ordernumber' maxlength="20" value='<?php echo $data["ordernumber"]?>' size='27' /> <font color="red">*</font>
                </td>
            </tr>
            <tr>
                <td class="label"><?php echo $fieldName["phonenumber"]?>:</td>
                <td>
                    <input type='text' name='phonenumber' maxlength="20" value='<?php echo $data["phonenumber"]?>' size='27' /> <font color="red">*</font>
                </td>
            </tr>
            <tr>
                <td class="label"><?php echo $fieldName["status"]?>:</td>
                <td>
                   <select name="status">
                       <?php foreach ($status as $k=>$v): ?>
                       <option value="<?php echo $k;?>"
                       <?php if($k == $data["status"]):?>
                            selected="selected"
                         <?php endif; ?>
                       ><?php echo $v;?></option>
                       <?php endforeach; ?>
                   </select>
                </td>
            </tr>
            <tr>
                <td class="label"><?php echo $fieldName["sendtype"]?>:</td>
                <td>
                    <select name="sendtype">
                        <?php foreach ($sendtype as $k=>$v): ?>
                            <option value="<?php echo $k;?>"
                                <?php if($k == $data["sendtype"]):?>
                                    selected="selected"
                                <?php endif; ?>
                            ><?php echo $v;?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="label"><?php echo $fieldName["content"]?>:</td>
                <td>
                    <textarea rows="10" cols="60" name="content"><?php echo $data["content"]?></textarea> <font color="red">*</font>
                </td>
            </tr>

            <input type="hidden" name="id" value="<?php echo $data["sms_id"];?>">

        </table>
        <div class="button-div">
            <input type="submit" value=" 确定 " />
        </div>
    </form>
</div>

<?php include_once "/assets/template/footer.php";?>

</body>
</html>