<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?php echo C('shopName');?> - 短信回收站 </title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="{:C('css')}/general.css" rel="stylesheet" type="text/css" />
<link href="{:C('css')}/main.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="{:C('js')}/jquery.js"></script>
</head>
<body>
<h1>
    <span class="action-span1"><a href="<?php echo U("Admin/Index/index")?>"><?php echo C('shopName');?></a></span>
    <span id="search_id" class="action-span1"> - 短信回收站 </span>
    <div style="clear:both"></div>
</h1>
<div class="form-div">
    <form action="" name="searchForm">
        <img src="{:C('img')}/icon_search.gif" width="26" height="22" border="0" alt="search" />

        <!--发送类型 -->
        <select name="sendtype">
            <?php foreach ($sendtype as $k=>$item): ?>
                <option value="<?php echo $k; ?>"><?php echo $item; ?> </option>
            <?php endforeach; ?>
        </select>

        <!--发送状态 -->
        <select name="status">
            <?php foreach ($status as $k=>$item): ?>
            <option value="<?php echo $k; ?>"><?php echo $item; ?> </option>
            <?php endforeach; ?>
        </select>

        <!-- 关键字 -->
        关键字 <input type="text" name="keyword" size="15" />
        <input type="submit" value=" 搜索 " class="button" />
    </form>
</div>

<!-- sms列表 -->
<form method="post" action="<?php echo U("Admin/Sms/batchRecovery");?>" name="sms">
    <div class="list-div" id="listDiv">
        <table cellpadding="3" cellspacing="1">
            <tr>
                <?php foreach ($fieldName as $v): ?>
                <th style="font-weight: bold"><?php echo $v; ?></th>
                <?php endforeach; ?>
            </tr>
            <?php foreach ($data as $sms): ?>
            <tr>
                <td align="center"><input type="checkbox" class="sms_id" name="sms_id[]" value="<?php echo $sms["sms_id"]?>"/><?php echo $sms["sms_id"]?></td>
                <td align="center"><?php echo $sms["ordernumber"]?></td>
                <td align="center"><?php echo $sms["phonenumber"]?></td>
                <td align="left"><?php echo $sms["content"]?></td>
                <td align="center"><?php echo $sendtype[$sms["sendtype"]]?></td>
                <td align="center"><?php echo $status[$sms["status"]]?></td>
                <td align="center"><?php echo date("Y-m-d H;i:s",$sms["created_at"])?></td>
                <td align="center">
                <a href="<?php echo U("Admin/Sms/recovery",array("id"=>$sms["sms_id"]));?>" >还原</a>|
                <a href="<?php echo U("Admin/Sms/del",array("id"=>$sms["sms_id"]));?>" >删除</a>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>

    <!-- 分页开始 -->
        <table id="page-table" cellspacing="0">
            <tr>
                <td width="50%"><input id="batch" type="submit" value="批量恢复"></td>
                <td align="center" nowrap="true">
                  <?php echo $page; ?>
                </td>
            </tr>
        </table>
    <!-- 分页结束 -->
    </div>
</form>

<script>
    $(function () {
        //单选不为真，取消全选
        var checkSize = 0;
        batchSelect(checkSize);
       $("#allCheck").click(function () {
          if($(this).attr("checked"))
          {
              $(".sms_id").attr("checked","checked");
              checkSize = $('.sms_id').size();
          }
          else
          {
              $(".sms_id").attr("checked","");
              checkSize = 0;
          }
           batchSelect(checkSize);
       });

        $('.sms_id').click(function () {

            if(!$(this).attr("checked"))
            {
                $("#allCheck").attr("checked","");
                checkSize--;
                if(checkSize < 0)
                {
                    checkSize = 0;
                }
//                alert(checkSize);
            }
            else
            {
                checkSize++;
                if(checkSize > $('.sms_id').size())
                {
                    checkSize = $('.sms_id').size();
                }
//                alert(checkSize);
                if(checkSize ==  $('.sms_id').size())
                {
                    $("#allCheck").attr("checked","checked");
                }
            }
            batchSelect(checkSize);
        });

    });
    //批量删除效果
    function batchSelect(num) {
        if(num > 0)
        {
            $('#batch').attr("disabled","");
        }
        else
        {
            $('#batch').attr("disabled","disabled");
        }
    }

</script>
<?php include_once "/assets/template/footer.php";?>
</body>
</html>